language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode # currently in active development, may or may not work for your project
  - ruby-head
env: ARUBA_TIMEOUT=120 RAILS_ENV=development AHN_ENV=development
notifications:
  irc: "irc.freenode.org#adhearsion"
