language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 3.1.0
  - ruby-head
before_install:
  - ruby -v # for (j)ruby-head
  - rvm @global @default do gem uninstall bundler -a -x --silent || true
  - gem install bundler -v '<2'
matrix:
  include:
    - rvm: jruby-9.1.17.0
      jdk: openjdk8
    - rvm: jruby-9.2.11.1
      jdk: openjdk11
      name: JRuby_92
    - rvm: jruby-head
      jdk: openjdk11
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - name: JRuby_92 # fails console launching features (ChildProcess::TimeoutError)
env:
  global:
    ARUBA_TIMEOUT: "120"
    AHN_ENV: "development"
    JRUBY_OPTS: "-J-Xmx512m"
notifications:
  slack:
    secure: Y7EqF/9FY7mca63c1DM7kEr34fNtFclWXJj9vLqVQJwR3rCDZUZSD8DlqHJDwE6KRCCDsSkyV4lihCim+GEM28CRcJir0AEUJhXHvIMckjH7n38W9OGN26RuJGZTapjgCSMOBeq0YpSe6dAnZeRpZRJxsTFtP5ptLD5RRjIMzZM=
