language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-9.1.2.0
  - ruby-head
jdk:
  - openjdk7 # for jruby
before_install:
  - gem install bundler
before_script: export JRUBY_OPTS="--server -J-Xss1024k -J-Xmx652m -J-XX:+UseConcMarkSweepGC"
matrix:
  allow_failures:
    - rvm: ruby-head
env: ARUBA_TIMEOUT=120 AHN_ENV=development
sudo: false
notifications:
  slack:
    secure: Y7EqF/9FY7mca63c1DM7kEr34fNtFclWXJj9vLqVQJwR3rCDZUZSD8DlqHJDwE6KRCCDsSkyV4lihCim+GEM28CRcJir0AEUJhXHvIMckjH7n38W9OGN26RuJGZTapjgCSMOBeq0YpSe6dAnZeRpZRJxsTFtP5ptLD5RRjIMzZM=
